### ISSUE TITLE
Bad range spec for IPv6 targets

### ISSUE THREAD

**Issue by hazcod** [robertdavidgraham/masscan#568] opened 2021-03-16 09:42 UTC
Hi, trying to run `masscan` against an example IPv6 range/address.
```shell
% masscan --open --ports 80 --range 2607:f0d0:1002:0051:0000:0000:0000:0004/128
ERROR: bad IP address/range: 2607:f0d0:1002:0051:0000:0000:0000:0004/128
FAIL: target IP address list empty
 [hint] try something like "--range 10.0.0.0/8"
 [hint] try something like "--range 192.168.0.100-192.168.0.200"

% masscan --open --ports 80 2607:f0d0:1002:0051:0000:0000:0000:0004
ERROR: bad IP address/range: 2607:f0d0:1002:0051:0000:0000:0000:0004
FAIL: target IP address list empty
 [hint] try something like "--range 10.0.0.0/8"
 [hint] try something like "--range 192.168.0.100-192.168.0.200"
```

**Comment by peterezzo** [comment] 2021-04-13 17:24
I ran into this same issue on 1.0.5 but building from src to 1.3.2 resolved it.

**Comment by robertdavidgraham** [comment] 2021-05-26 21:01
I'm closing this out because I think it's been resolved. At least, with the latest version, I can't reproduce.

**Closed by robertdavidgraham** 2021-05-26 21:01 UTC
